/*
  Warnings:

  - The values [FILLING,AWAITING_INPUT,REVIEWING_CHANGES,READY_TO_SIGN,AWAITING_SIGNATURE,SIGNING_COMPLETE] on the enum `nda_workflow_state` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
BEGIN;
CREATE TYPE "nda_workflow_state_new" AS ENUM ('DRAFT', 'AWAITING_PARTY_B_REVIEW', 'AWAITING_PARTY_A_REVIEW', 'AWAITING_PARTY_B_SIGNATURE', 'AWAITING_PARTY_A_SIGNATURE', 'COMPLETE');
ALTER TABLE "nda_drafts" ALTER COLUMN "workflow_state" DROP DEFAULT;
ALTER TABLE "nda_drafts" ALTER COLUMN "workflow_state" TYPE "nda_workflow_state_new" USING (
  CASE "workflow_state"::text
    WHEN 'FILLING' THEN 'DRAFT'
    WHEN 'AWAITING_INPUT' THEN 'AWAITING_PARTY_B_REVIEW'
    WHEN 'REVIEWING_CHANGES' THEN 'AWAITING_PARTY_A_REVIEW'
    WHEN 'READY_TO_SIGN' THEN 'AWAITING_PARTY_B_SIGNATURE'
    WHEN 'AWAITING_SIGNATURE' THEN 'AWAITING_PARTY_A_SIGNATURE'
    WHEN 'SIGNING_COMPLETE' THEN 'COMPLETE'
    WHEN 'DRAFT' THEN 'DRAFT'
    WHEN 'AWAITING_PARTY_B_REVIEW' THEN 'AWAITING_PARTY_B_REVIEW'
    WHEN 'AWAITING_PARTY_A_REVIEW' THEN 'AWAITING_PARTY_A_REVIEW'
    WHEN 'AWAITING_PARTY_B_SIGNATURE' THEN 'AWAITING_PARTY_B_SIGNATURE'
    WHEN 'AWAITING_PARTY_A_SIGNATURE' THEN 'AWAITING_PARTY_A_SIGNATURE'
    WHEN 'COMPLETE' THEN 'COMPLETE'
    ELSE 'DRAFT'
  END::"nda_workflow_state_new"
);
ALTER TYPE "nda_workflow_state" RENAME TO "nda_workflow_state_old";
ALTER TYPE "nda_workflow_state_new" RENAME TO "nda_workflow_state";
DROP TYPE "nda_workflow_state_old";
ALTER TABLE "nda_drafts" ALTER COLUMN "workflow_state" SET DEFAULT 'DRAFT';
COMMIT;

-- AlterTable
ALTER TABLE "nda_drafts" ADD COLUMN     "last_edited_by" TEXT,
ALTER COLUMN "workflow_state" SET DEFAULT 'DRAFT';
